name: Test
on:
  pull_request:
    branches:
      - main
jobs:
  validate-pr-title:
    name: Validate Conventional Commits PR
    if: github.event.pull_request.draft == false
    runs-on: ubuntu-latest
    steps:
      - uses: crazy-max/ghaction-dump-context@v1
      - uses: amannn/action-semantic-pull-request@v3.4.6
        with:
          types: |
            fix
            feat
            norelease
            chore
          validateSingleCommit: true
        env:
          GITHUB_TOKEN: ${{ github.token }}
  test:
    if: github.event.pull_request.draft == false
    name: Test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Setup cache
        uses: actions/cache@v3
        with:
          # In order:
          # * go Module download cache
          # * go Build cache (Linux)
          path: |
            ~/go/pkg/mod
            ~/.cache/go-build
          key: ${{ runner.os }}-go-${{ hashFiles('**/go.sum') }}
          restore-keys: |
            ${{ runner.os }}-go-
      - name: Setup go
        uses: actions/setup-go@v4
        with:
          go-version: 1.20
      - name: Compile and Test
        run: |
          git config --global url."https://${{ secrets.AUTOMATION_PAT }}@github.com".insteadOf "https://github.com"
          go mod download
          go build ./...
          cd test
          go test